-- DropForeignKey
ALTER TABLE "HoaDon" DROP CONSTRAINT "HoaDon_MaNV_fkey";

-- AlterTable
ALTER TABLE "HoaDon" ALTER COLUMN "MaNV" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "HoaDon" ADD CONSTRAINT "HoaDon_MaNV_fkey" FOREIGN KEY ("MaNV") REFERENCES "NhanVien"("MaNV") ON DELETE SET NULL ON UPDATE CASCADE;
